# Generated by Django 5.2.6 on 2025-09-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinville', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/avatares/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='interesses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
