# Generated by Django 5.2.6 on 2025-10-09 01:02

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinville', '0002_usuario_avatar_usuario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 9, 1, 2, 11, 501267, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/covers/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AvaliacaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(limit_choices_to={'tipo_usuario': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(limit_choices_to={'tipo_usuario': 'USUARIO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_avaliacao'],
                'unique_together': {('empresa', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='FollowEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_seguido', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(limit_choices_to={'tipo_usuario': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(limit_choices_to={'tipo_usuario': 'USUARIO'}, on_delete=django.db.models.deletion.CASCADE, related_name='seguindo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_seguido'],
                'unique_together': {('usuario', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='InteresseEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_interesse', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessados', to='joinville.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_interesse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_interesse'],
                'unique_together': {('evento', 'usuario')},
            },
        ),
    ]
